import * as stylex from "@stylexjs/stylex";

const styles = stylex.create({
  form: { display: "grid", gap: "1rem", width: "100%" },
  field: { display: "grid", gap: "0.35rem" },
  label: { fontSize: "0.9rem", fontWeight: 700 },
  control: {
    backgroundAttachment: "scroll",
    backgroundClip: "border-box",
    backgroundColor: "var(--suite-profile-input-background, transparent)",
    backgroundImage: "none",
    backgroundOrigin: "padding-box",
    backgroundPosition: "0% 0%",
    backgroundRepeat: "repeat",
    backgroundSize: "auto auto",
    borderColor: "var(--suite-profile-line, currentColor)",
    borderStyle: "solid",
    borderWidth: "1px",
    borderImageSource: "none",
    borderImageSlice: "100%",
    borderImageWidth: 1,
    borderImageOutset: 0,
    borderImageRepeat: "stretch",
    borderRadius: "0.35rem",
    color: "inherit",
    fontFamily: "inherit",
    fontSize: "inherit",
    fontStretch: "inherit",
    fontStyle: "inherit",
    fontVariant: "inherit",
    fontWeight: "inherit",
    fontFeatureSettings: "inherit",
    fontKerning: "inherit",
    fontLanguageOverride: "inherit",
    fontOpticalSizing: "inherit",
    fontSizeAdjust: "inherit",
    fontVariationSettings: "inherit",
    lineHeight: 1.4,
    minWidth: 0,
    paddingBottom: "0.7rem",
    paddingLeft: "0.75rem",
    paddingRight: "0.75rem",
    paddingTop: "0.7rem",
    width: "100%",
  },
  textarea: { resize: "vertical" },
  focus: {
    outlineColor: { default: null, ":focus-visible": "var(--suite-profile-focus, currentColor)" },
    outlineOffset: { default: null, ":focus-visible": "2px" },
    outlineStyle: { default: null, ":focus-visible": "solid" },
    outlineWidth: { default: null, ":focus-visible": "2px" },
  },
  readonly: {
    color: "var(--suite-profile-muted, currentColor)",
    cursor: "default",
    opacity: 0.72,
  },
  button: {
    backgroundAttachment: "scroll",
    backgroundClip: "border-box",
    backgroundColor: "var(--suite-profile-button-background, currentColor)",
    backgroundImage: "none",
    backgroundOrigin: "padding-box",
    backgroundPosition: "0% 0%",
    backgroundRepeat: "repeat",
    backgroundSize: "auto auto",
    borderColor: "var(--suite-profile-button-background, currentColor)",
    borderStyle: "solid",
    borderWidth: "1px",
    borderImageSource: "none",
    borderImageSlice: "100%",
    borderImageWidth: 1,
    borderImageOutset: 0,
    borderImageRepeat: "stretch",
    borderRadius: "999px",
    color: "var(--suite-profile-button-foreground, Canvas)",
    cursor: { default: "pointer", ":disabled": "wait" },
    fontFamily: "inherit",
    fontSize: "inherit",
    fontStretch: "inherit",
    fontStyle: "inherit",
    fontVariant: "inherit",
    fontWeight: 700,
    fontFeatureSettings: "inherit",
    fontKerning: "inherit",
    fontLanguageOverride: "inherit",
    fontOpticalSizing: "inherit",
    fontSizeAdjust: "inherit",
    fontVariationSettings: "inherit",
    lineHeight: "inherit",
    justifySelf: "start",
    opacity: { default: null, ":disabled": 0.6 },
    paddingBottom: "0.65rem",
    paddingLeft: "1rem",
    paddingRight: "1rem",
    paddingTop: "0.65rem",
  },
  error: {
    color: "var(--suite-profile-error, #a83232)",
    fontSize: "0.9rem",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
  },
});

export const profileFormClasses = {
  button: stylex.props(styles.button, styles.focus).className,
  control: stylex.props(styles.control, styles.focus).className,
  email: stylex.props(styles.control, styles.focus, styles.readonly).className,
  error: stylex.props(styles.error).className,
  field: stylex.props(styles.field).className,
  form: stylex.props(styles.form).className,
  label: stylex.props(styles.label).className,
  textarea: stylex.props(styles.control, styles.focus, styles.textarea).className,
} as const;
